[package]
name = "stream_fs"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true
description = "Stream File System - a file system in a file"
homepage = "https://github.com/sunbeam60/stream_fs"
keywords = ["filesystem", "embedded", "streams", "storage"]
categories = ["filesystem", "data-structures"]

[dependencies]
fs2 = "0.4.3"
