[package]
name = "sfs_cl"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true
description = "Command line tool for the Stream File System"

[[bin]]
name = "sfs"
path = "src/main.rs"

[dependencies]
stream_fs.workspace = true
