[package]
name = "sfs_cl"
version = "0.1.0"
edition = "2021"
description = "Command line tool for the Stream File System"
license = "MIT OR Apache-2.0"
repository = "https://github.com/sunbeam60/stream_fs"
publish = false

[[bin]]
name = "sfs"
path = "src/main.rs"

[dependencies]
stream_fs = { path = "../stream_fs", version = "0.1.0" }
