/* Generated by cbindgen — do not edit manually.
 *
 * Stream File System C API
 */

#ifndef STREAM_FS_C_H
#define STREAM_FS_C_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// Opaque handle to an open SFS file.
// C consumers see `SfsFile*` — the internal layout is never exposed.
typedef struct SfsFile SfsFile;

// Opaque directory listing returned by `sfs_list`.
typedef struct SfsList SfsList;

// Opaque verification result returned by `sfs_verify`.
typedef struct SfsVerifyResult SfsVerifyResult;

const char *sfs_last_error_message(void);

// # Safety
// `path` must be a valid, null-terminated UTF-8 string.
struct SfsFile *sfs_create(const char *path, uint8_t block_index_width, uint8_t block_size_shift);

// Create a new SFS file with a custom compressed block size shift for compression.
// `compressed_block_size_shift` must be >= `block_size_shift`.
//
// # Safety
// `path` must be a valid, null-terminated UTF-8 string.
struct SfsFile *sfs_create_with_cbss(const char *path,
                                     uint8_t block_index_width,
                                     uint8_t block_size_shift,
                                     uint8_t compressed_block_size_shift);

// Open an existing SFS file. mode: 0=READ, 1=WRITE.
//
// # Safety
// `path` must be a valid, null-terminated UTF-8 string.
struct SfsFile *sfs_open(const char *path, int mode);

// Create a new encrypted SFS file. `password` is a null-terminated UTF-8 string.
// Returns NULL on error.
//
// # Safety
// `path` and `password` must be valid, null-terminated UTF-8 strings.
struct SfsFile *sfs_create_encrypted(const char *path,
                                     uint8_t block_index_width,
                                     uint8_t block_size_shift,
                                     const char *password);

// Open an existing encrypted SFS file. mode: 0=READ, 1=WRITE.
// `password` is a null-terminated UTF-8 string.
// Returns NULL on error (`sfs_last_error_message` will indicate wrong password
// or missing password).
//
// # Safety
// `path` and `password` must be valid, null-terminated UTF-8 strings.
struct SfsFile *sfs_open_encrypted(const char *path, int mode, const char *password);

// Check whether the SFS file has encryption enabled.
// Returns 1 if encrypted, 0 if not.
//
// # Safety
// `handle` must be a live `SfsFile` pointer.
int sfs_is_encrypted(struct SfsFile *handle);

// Close the SFS file, flushing any open stream handles.
// Returns 0 on success, -1 on error. The handle is always consumed
// regardless of the return value — callers must not reuse it.
//
// # Safety
// `handle` must be a valid pointer returned by `sfs_create` or `sfs_open`,
// and must not have been closed already.
int sfs_close(struct SfsFile *handle);

// Get the compressed block size shift. Returns 0 if compression is not configured.
//
// # Safety
// `handle` must be a live `SfsFile` pointer.
uint8_t sfs_compressed_block_size_shift(struct SfsFile *handle);

// # Safety
// `handle` must be a live `SfsFile` pointer. `path` must be a valid C string.
int sfs_mkdir(struct SfsFile *handle, const char *path);

// # Safety
// `handle` must be a live `SfsFile` pointer. `path` must be a valid C string.
int sfs_rmdir(struct SfsFile *handle, const char *path);

// # Safety
// `handle` must be a live `SfsFile` pointer. Both path arguments must be valid C strings.
int sfs_rename_dir(struct SfsFile *handle, const char *old_path, const char *new_path);

// # Safety
// `handle` must be a live `SfsFile` pointer. `path` must be a valid C string.
struct SfsList *sfs_list(struct SfsFile *handle, const char *path);

// # Safety
// `list` must be a valid pointer returned by `sfs_list` and not yet freed.
int sfs_list_count(struct SfsList *list);

// # Safety
// `list` must be a valid pointer returned by `sfs_list` and not yet freed.
const char *sfs_list_entry_name(struct SfsList *list, int index);

// # Safety
// `list` must be a valid pointer returned by `sfs_list` and not yet freed.
int sfs_list_entry_type(struct SfsList *list, int index);

// # Safety
// `list` must be a valid pointer returned by `sfs_list` and not yet freed.
void sfs_list_free(struct SfsList *list);

// Run integrity verification across all layers. Returns a result handle (NULL on error).
// Use sfs_verify_count/sfs_verify_issue to read issues, then sfs_verify_free to release.
//
// # Safety
// `handle` must be a live `SfsFile` pointer.
struct SfsVerifyResult *sfs_verify(struct SfsFile *handle);

// # Safety
// `result` must be a valid pointer returned by `sfs_verify` and not yet freed.
int sfs_verify_count(struct SfsVerifyResult *result);

// # Safety
// `result` must be a valid pointer returned by `sfs_verify` and not yet freed.
const char *sfs_verify_issue(struct SfsVerifyResult *result, int index);

// # Safety
// `result` must be a valid pointer returned by `sfs_verify` and not yet freed.
void sfs_verify_free(struct SfsVerifyResult *result);

// Create a new stream and open it for writing. Returns handle ID or -1.
// `compressed`: non-zero to create a compressed stream (requires cbss > 0).
//
// # Safety
// `handle` must be a live `SfsFile` pointer. `path` must be a valid C string.
int64_t sfs_create_stream(struct SfsFile *handle, const char *path, int32_t compressed);

// Open an existing stream. mode: 0=READ, 1=WRITE. Returns handle ID or -1.
//
// # Safety
// `handle` must be a live `SfsFile` pointer. `path` must be a valid C string.
int64_t sfs_open_stream(struct SfsFile *handle, const char *path, int mode);

// Close a stream handle.
//
// # Safety
// `handle` must be a live `SfsFile` pointer. `stream` must be an open stream handle ID.
int sfs_close_stream(struct SfsFile *handle, int64_t stream);

// Delete a stream by path. Must not be currently open.
//
// # Safety
// `handle` must be a live `SfsFile` pointer. `path` must be a valid C string.
int sfs_delete_stream(struct SfsFile *handle, const char *path);

// Rename/move a stream by path. Must not be currently open.
//
// # Safety
// `handle` must be a live `SfsFile` pointer. Both path arguments must be valid C strings.
int sfs_rename_stream(struct SfsFile *handle, const char *old_path, const char *new_path);

// Read up to `len` bytes. Returns bytes read or -1 on error.
//
// # Safety
// `handle` must be a live `SfsFile` pointer. `stream` must be an open stream handle ID.
// `buf` must point to at least `len` writable bytes.
int64_t sfs_stream_read(struct SfsFile *handle, int64_t stream, uint8_t *buf, uint64_t len);

// Write `len` bytes. Returns bytes written or -1 on error.
//
// # Safety
// `handle` must be a live `SfsFile` pointer. `stream` must be an open stream handle ID.
// `buf` must point to at least `len` readable bytes.
int64_t sfs_stream_write(struct SfsFile *handle, int64_t stream, const uint8_t *buf, uint64_t len);

// Set the head position. Returns 0 or -1.
//
// # Safety
// `handle` must be a live `SfsFile` pointer. `stream` must be an open stream handle ID.
int sfs_stream_seek(struct SfsFile *handle, int64_t stream, uint64_t pos);

// Get the current head position. Returns position or -1 on error.
//
// # Safety
// `handle` must be a live `SfsFile` pointer. `stream` must be an open stream handle ID.
int64_t sfs_stream_tell(struct SfsFile *handle, int64_t stream);

// Get the stream length. Returns length or -1 on error.
//
// # Safety
// `handle` must be a live `SfsFile` pointer. `stream` must be an open stream handle ID.
int64_t sfs_stream_length(struct SfsFile *handle, int64_t stream);

// Truncate a stream. Returns 0 or -1.
//
// # Safety
// `handle` must be a live `SfsFile` pointer. `stream` must be an open stream handle ID.
int sfs_stream_truncate(struct SfsFile *handle, int64_t stream, uint64_t new_len);

// Pre-allocate storage for a stream. Returns 0 or -1.
//
// # Safety
// `handle` must be a live `SfsFile` pointer. `stream` must be an open stream handle ID.
int sfs_stream_reserve(struct SfsFile *handle, int64_t stream, uint64_t n_bytes);

// Get the reserved capacity of a stream. Returns capacity or -1 on error.
//
// # Safety
// `handle` must be a live `SfsFile` pointer. `stream` must be an open stream handle ID.
int64_t sfs_stream_reserved(struct SfsFile *handle, int64_t stream);

// Check whether a stream is compressed. Returns 1 if compressed, 0 if not, -1 on error.
//
// # Safety
// `handle` must be a live `SfsFile` pointer. `stream` must be an open stream handle ID.
int sfs_stream_is_compressed(struct SfsFile *handle, int64_t stream);

#endif  /* STREAM_FS_C_H */
