/* Generated by cbindgen — do not edit manually.
 *
 * Yak C API
 */

#ifndef YAK_C_H
#define YAK_C_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// Opaque handle to an open Yak file.
// C consumers see `YakFile*` — the internal layout is never exposed.
typedef struct YakFile YakFile;

// Opaque directory listing returned by `yak_list`.
typedef struct YakList YakList;

// Opaque verification result returned by `yak_verify`.
typedef struct YakVerifyResult YakVerifyResult;

const char *yak_last_error_message(void);

// # Safety
// `path` must be a valid, null-terminated UTF-8 string.
struct YakFile *yak_create(const char *path, uint8_t block_index_width, uint8_t block_size_shift);

// Create a new Yak file with a custom compressed block size shift for compression.
// `compressed_block_size_shift` must be >= `block_size_shift`.
//
// # Safety
// `path` must be a valid, null-terminated UTF-8 string.
struct YakFile *yak_create_with_cbss(const char *path,
                                     uint8_t block_index_width,
                                     uint8_t block_size_shift,
                                     uint8_t compressed_block_size_shift);

// Open an existing Yak file. mode: 0=READ, 1=WRITE.
//
// # Safety
// `path` must be a valid, null-terminated UTF-8 string.
struct YakFile *yak_open(const char *path, int mode);

// Create a new encrypted Yak file. `password` is a null-terminated UTF-8 string.
// Returns NULL on error.
//
// # Safety
// `path` and `password` must be valid, null-terminated UTF-8 strings.
struct YakFile *yak_create_encrypted(const char *path,
                                     uint8_t block_index_width,
                                     uint8_t block_size_shift,
                                     const char *password);

// Open an existing encrypted Yak file. mode: 0=READ, 1=WRITE.
// `password` is a null-terminated UTF-8 string.
// Returns NULL on error (`yak_last_error_message` will indicate wrong password
// or missing password).
//
// # Safety
// `path` and `password` must be valid, null-terminated UTF-8 strings.
struct YakFile *yak_open_encrypted(const char *path, int mode, const char *password);

// Check whether the Yak file has encryption enabled.
// Returns 1 if encrypted, 0 if not.
//
// # Safety
// `handle` must be a live `YakFile` pointer.
int yak_is_encrypted(struct YakFile *handle);

// Close the Yak file, flushing any open stream handles.
// Returns 0 on success, -1 on error. The handle is always consumed
// regardless of the return value — callers must not reuse it.
//
// # Safety
// `handle` must be a valid pointer returned by `yak_create` or `yak_open`,
// and must not have been closed already.
int yak_close(struct YakFile *handle);

// Get the compressed block size shift. Returns 0 if compression is not configured.
//
// # Safety
// `handle` must be a live `YakFile` pointer.
uint8_t yak_compressed_block_size_shift(struct YakFile *handle);

// # Safety
// `handle` must be a live `YakFile` pointer. `path` must be a valid C string.
int yak_mkdir(struct YakFile *handle, const char *path);

// # Safety
// `handle` must be a live `YakFile` pointer. `path` must be a valid C string.
int yak_rmdir(struct YakFile *handle, const char *path);

// # Safety
// `handle` must be a live `YakFile` pointer. Both path arguments must be valid C strings.
int yak_rename_dir(struct YakFile *handle, const char *old_path, const char *new_path);

// # Safety
// `handle` must be a live `YakFile` pointer. `path` must be a valid C string.
struct YakList *yak_list(struct YakFile *handle, const char *path);

// # Safety
// `list` must be a valid pointer returned by `yak_list` and not yet freed.
int yak_list_count(struct YakList *list);

// # Safety
// `list` must be a valid pointer returned by `yak_list` and not yet freed.
const char *yak_list_entry_name(struct YakList *list, int index);

// # Safety
// `list` must be a valid pointer returned by `yak_list` and not yet freed.
int yak_list_entry_type(struct YakList *list, int index);

// # Safety
// `list` must be a valid pointer returned by `yak_list` and not yet freed.
void yak_list_free(struct YakList *list);

// Run integrity verification across all layers. Returns a result handle (NULL on error).
// Use yak_verify_count/yak_verify_issue to read issues, then yak_verify_free to release.
//
// # Safety
// `handle` must be a live `YakFile` pointer.
struct YakVerifyResult *yak_verify(struct YakFile *handle);

// # Safety
// `result` must be a valid pointer returned by `yak_verify` and not yet freed.
int yak_verify_count(struct YakVerifyResult *result);

// # Safety
// `result` must be a valid pointer returned by `yak_verify` and not yet freed.
const char *yak_verify_issue(struct YakVerifyResult *result, int index);

// # Safety
// `result` must be a valid pointer returned by `yak_verify` and not yet freed.
void yak_verify_free(struct YakVerifyResult *result);

// Optimize a Yak file by rewriting it without free blocks.
// Removes free blocks and rewrites streams contiguously for maximum locality.
// Returns the number of bytes saved, or -1 on error.
// For unencrypted files, pass NULL for `password`.
// For encrypted files, `password` must be a valid null-terminated UTF-8 string.
//
// # Safety
// `path` must be a valid, null-terminated UTF-8 string.
// `password`, if non-null, must be a valid, null-terminated UTF-8 string.
int64_t yak_optimize(const char *path, const char *password);

// Create a new stream and open it for writing. Returns handle ID or -1.
// `compressed`: non-zero to create a compressed stream (requires cbss > 0).
//
// # Safety
// `handle` must be a live `YakFile` pointer. `path` must be a valid C string.
int64_t yak_create_stream(struct YakFile *handle, const char *path, int32_t compressed);

// Open an existing stream. mode: 0=READ, 1=WRITE. Returns handle ID or -1.
//
// # Safety
// `handle` must be a live `YakFile` pointer. `path` must be a valid C string.
int64_t yak_open_stream(struct YakFile *handle, const char *path, int mode);

// Close a stream handle.
//
// # Safety
// `handle` must be a live `YakFile` pointer. `stream` must be an open stream handle ID.
int yak_close_stream(struct YakFile *handle, int64_t stream);

// Delete a stream by path. Must not be currently open.
//
// # Safety
// `handle` must be a live `YakFile` pointer. `path` must be a valid C string.
int yak_delete_stream(struct YakFile *handle, const char *path);

// Rename/move a stream by path. Must not be currently open.
//
// # Safety
// `handle` must be a live `YakFile` pointer. Both path arguments must be valid C strings.
int yak_rename_stream(struct YakFile *handle, const char *old_path, const char *new_path);

// Read up to `len` bytes. Returns bytes read or -1 on error.
//
// # Safety
// `handle` must be a live `YakFile` pointer. `stream` must be an open stream handle ID.
// `buf` must point to at least `len` writable bytes.
int64_t yak_stream_read(struct YakFile *handle, int64_t stream, uint8_t *buf, uint64_t len);

// Write `len` bytes. Returns bytes written or -1 on error.
//
// # Safety
// `handle` must be a live `YakFile` pointer. `stream` must be an open stream handle ID.
// `buf` must point to at least `len` readable bytes.
int64_t yak_stream_write(struct YakFile *handle, int64_t stream, const uint8_t *buf, uint64_t len);

// Set the head position. Returns 0 or -1.
//
// # Safety
// `handle` must be a live `YakFile` pointer. `stream` must be an open stream handle ID.
int yak_stream_seek(struct YakFile *handle, int64_t stream, uint64_t pos);

// Get the current head position. Returns position or -1 on error.
//
// # Safety
// `handle` must be a live `YakFile` pointer. `stream` must be an open stream handle ID.
int64_t yak_stream_tell(struct YakFile *handle, int64_t stream);

// Get the stream length. Returns length or -1 on error.
//
// # Safety
// `handle` must be a live `YakFile` pointer. `stream` must be an open stream handle ID.
int64_t yak_stream_length(struct YakFile *handle, int64_t stream);

// Truncate a stream. Returns 0 or -1.
//
// # Safety
// `handle` must be a live `YakFile` pointer. `stream` must be an open stream handle ID.
int yak_stream_truncate(struct YakFile *handle, int64_t stream, uint64_t new_len);

// Pre-allocate storage for a stream. Returns 0 or -1.
//
// # Safety
// `handle` must be a live `YakFile` pointer. `stream` must be an open stream handle ID.
int yak_stream_reserve(struct YakFile *handle, int64_t stream, uint64_t n_bytes);

// Get the reserved capacity of a stream. Returns capacity or -1 on error.
//
// # Safety
// `handle` must be a live `YakFile` pointer. `stream` must be an open stream handle ID.
int64_t yak_stream_reserved(struct YakFile *handle, int64_t stream);

// Check whether a stream is compressed. Returns 1 if compressed, 0 if not, -1 on error.
//
// # Safety
// `handle` must be a live `YakFile` pointer. `stream` must be an open stream handle ID.
int yak_stream_is_compressed(struct YakFile *handle, int64_t stream);

#endif  /* YAK_C_H */
